[tool.poetry]
name = "extract"
version = "0.1.0"
description = ""
authors = ["Severin Simmler <severin.simmler@stud-mail.uni-wuerzburg.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
gensim = "^3.8.1"
syntok = "^1.2.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
train-fasttext = "extract:scripts.train_fasttext.run"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
