[tool.poetry]
name = "extract"
version = "0.1.0"
description = ""
authors = ["Severin Simmler <severin.simmler@stud-mail.uni-wuerzburg.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
spacy = "^2.2.1"
regex = "^2019.8.19"
gensim = "^3.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
