[tool.poetry]
name = "extract"
version = "0.1.0"
description = "Extracting information from unstructured text."
authors = ["Severin Simmler <severin.simmler@stud-mail.uni-wuerzburg.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
gensim = "^3.8.1"
syntok = "^1.2.1"
scikit-learn = "^0.21.3"
scipy = "^1.3.1"

[tool.poetry.dev-dependencies]
jupyterlab = "^1.2.1"

[tool.poetry.scripts]
fasttext = "extract:scripts.fasttext.run"
word2vec = "extract:scripts.word2vec.run"
tfidf = "extract:scripts.tfidf.run"
tokenizer = "extract:scripts.tokenize_corpus.run"
corpus-filter = "extract:scripts.filter_corpus.run"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
